// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3iedt20wCPz1pzUHgdiVJytNIuqXqBvg',
    appId: '1:612618204451:android:78d9917e9c0c9f0dac0896',
    messagingSenderId: '612618204451',
    projectId: 'facebooklogin-72f6c',
    databaseURL: 'https://facebooklogin-72f6c-default-rtdb.firebaseio.com',
    storageBucket: 'facebooklogin-72f6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_qN9M8vwT465zfb_xDvCJQ9wYkkZPiQ8',
    appId: '1:612618204451:ios:310da57767d046e5ac0896',
    messagingSenderId: '612618204451',
    projectId: 'facebooklogin-72f6c',
    databaseURL: 'https://facebooklogin-72f6c-default-rtdb.firebaseio.com',
    storageBucket: 'facebooklogin-72f6c.appspot.com',
    iosBundleId: 'com.realtimechat.realtimechat',
  );
}
